/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconSelect: typeof import('./src/components/IconSelect/index.vue')['default']
    Iframe: typeof import('./src/components/Iframe/index.vue')['default']
    Indve: typeof import('./src/components/Layout/indve.vue')['default']
    Item: typeof import('./src/components/Layout/SiderBar/item.vue')['default']
    NavBar: typeof import('./src/components/Layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderBar: typeof import('./src/components/Layout/SiderBar/index.vue')['default']
    TagsView: typeof import('./src/components/Layout/TagsView.vue')['default']
    TreeSelect: typeof import('./src/components/TreeSelect/index.vue')['default']
  }
}
