/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconSelect: typeof import('./../components/IconSelect/index.vue')['default']
    Iframe: typeof import('./../components/Iframe/index.vue')['default']
    Indve: typeof import('./../components/Layout/indve.vue')['default']
    Item: typeof import('./../components/Layout/SiderBar/item.vue')['default']
    NavBar: typeof import('./../components/Layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderBar: typeof import('./../components/Layout/SiderBar/index.vue')['default']
    TagsView: typeof import('./../components/Layout/TagsView.vue')['default']
    TreeSelect: typeof import('./../components/TreeSelect/index.vue')['default']
  }
}
